// action all blog
export const FETCH_ALL_BLOG = 'FETCH_ALL_BLOG';
export const FETCHING_ALL_BLOG = 'FETCHING_ALL_BLOG';
export const SET_ALL_BLOG = 'SET_ALL_BLOG';
export const FETCHED_ALL_BLOG = 'FETCHED_ALL_BLOG';
export const FETCH_ALL_BLOG_SUCCESS = 'FETCH_ALL_BLOG_SUCCESS';
export const FETCH_ALL_BLOG_FAILED = 'FETCH_ALL_BLOG_FAILED';
export const RESET_ALL_STATUS_FETCH_BLOG = 'RESET_ALL_STATUS_FETCH_BLOG';

// action blog
export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCHING_BLOG = 'FETCHING_BLOG';
export const SET_BLOG = 'SET_BLOG';
export const SET_RELATED_BLOGS = 'SET_RELATED_BLOGS';
export const FETCHED_BLOG = 'FETCHED_BLOG';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED';
export const RESET_STATUS_FETCH_BLOG = 'RESET_STATUS_FETCH_BLOG';

// action blogs with category
export const FETCH_BLOGS_WITH_CATEGORY = 'FETCH_BLOGS_WITH_CATEGORY';
export const FETCHING_BLOGS_WITH_CATEGORY = 'FETCHING_BLOGS_WITH_CATEGORY';
export const SET_BLOGS_WITH_CATEGORY = 'SET_BLOGS_WITH_CATEGORY';
export const FETCHED_BLOGS_WITH_CATEGORY = 'FETCHED_BLOGS_WITH_CATEGORY';
export const FETCH_BLOGS_WITH_CATEGORY_SUCCESS =
  'FETCH_BLOGS_WITH_CATEGORY_SUCCESS';
export const FETCH_BLOGS_WITH_CATEGORY_FAILED =
  'FETCH_BLOGS_WITH_CATEGORY_FAILED';
export const RESET_STATUS_FETCH_BLOGS_WITH_CATEGORY =
  'RESET_STATUS_FETCH_BLOGS_WITH_CATEGORY';
