export const FETCH_CART = 'FETCH_CART';
export const FETCHING_CART = 'FETCHING_CART';
export const SET_CART = 'SET_CART';
export const FETCHED_CART = 'FETCHED_CART';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR';
export const FETCH_CART_RESET_STATUS = 'FETCH_CART_RESET_STATUS';
// 222 ACTION ADD ACRT
export const ADD_CART = 'ADD_CART';
export const ADDING_CART = 'ADDING_CART';
export const ADDED_CART = 'ADDED_CART';
export const ADD_CART_CUCCESS = 'ADD_CART_CUCCESS';
export const ADD_CART_FAILED = 'ADD_CART_FAILED';
export const ADD_CART_RESET_STATUS_ADDING = 'ADD_CART_RESET_STATUS_ADDING';

// 333 ACTION DELETE CART
export const DELETE_CART = 'DELETE_CART';
export const DELETING_CART = 'DELETING_CART';
export const DELETED_CART = 'DELETED_CART';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILED = 'DELETE_CART_FAILED';
export const RESET_STATUS_DELETE_CART = 'RESET_STATUS_DELETE_CART';

/// 444 ACTION UPDATE_CART
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATING_CART = 'UPDATING_CART ';
export const UPDATED_CART = 'UPDATED_CART';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILED = 'UPDATE_CART_FAILED';
export const RESET_STATUS_UPDATE_CART = 'RESET_STATUS_UPDATE_CART';
