export const ORDER_PRODUCT = 'ORDER_PRODUCT';
export const ORDERING_PRODUCT = 'ORDERING_PRODUCT';
export const ORDERED_PRODUCT = 'ORDERED_PRODUCT';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAILED = 'ORDER_PRODUCT_FAILED';
