export const FETCH_CART = 'FETCH_CART';
export const FETCHING_CART = 'FETCHING_CART';
export const SET_CART = 'SET_CART';
export const FETCHED_CART = 'FETCHED_CART';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR';
export const FETCH_CART_RESET_STATUS = 'FETCH_CART_RESET_STATUS';

export const ADD_CART = 'ADD_CART';
export const ADDING_CART = 'ADDING_CART';
export const ADDED_CART = 'ADDED_CART';
export const ADD_CART_CUCCESS = 'ADD_CART_CUCCESS';
export const ADD_CART_FAILED = 'ADD_CART_FAILED';
export const ADD_CART_RESET_STATUS_ADDING = 'ADD_CART_RESET_STATUS_ADDING';
