export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCHING_BLOG = 'FETCHING_BLOG';
export const SET_BLOG = 'SET_BLOG';
export const FETCHED_BLOG = 'FETCHED_BLOG';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED';
export const RESET_STATUS_FETCH_BLOG = 'RESET_STATUS_FETCH_BLOG';
