export const FETCH_REPORT_USER = 'FETCH_REPORT_USER';
export const FETCH_REPORT_PRODUCT = 'FETCH_REPORT_PRODUCT';
export const FETCH_REPORT_PRODUCT_CATEGORY = 'FETCH_REPORT_PRODUCT_CATEGORY';
export const FETCH_REPORT_ORDER = 'FETCH_REPORT_ORDER';

export const FETCHING_REPORT_USER = 'FETCHING_REPORT_USER';
export const FETCHING_REPORT_PRODUCT = 'FETCHING_REPORT_PRODUCT';
export const FETCHING_REPORT_PRODUCT_CATEGORY =
  'FETCHING_REPORT_PRODUCT_CATEGORY';
export const FETCHING_REPORT_ORDER = 'FETCHING_REPORT_ORDER';

export const FETCHED_REPORT_USER = 'FETCHED_REPORT_USER';
export const FETCHED_REPORT_PRODUCT = 'FETCHED_REPORT_PRODUCT';
export const FETCHED_REPORT_PRODUCT_CATEGORY =
  'FETCHED_REPORT_PRODUCT_CATEGORY';
export const FETCHED_REPORT_ORDER = 'FETCHED_REPORT_ORDER';

export const HANDLER_SET_REPORT_USER = 'HANDLER_SET_REPORT_USER';
export const HANDLER_SET_REPORT_PRODUCT = 'HANDLER_SET_REPORT_PRODUCT';
export const HANDLER_SET_REPORT_PRODUCT_CATEGORY =
  'HANDLER_SET_REPORT_PRODUCT_CATEGORY';
export const HANDLER_SET_REPORT_ORDER = 'HANDLER_SET_REPORT_ORDER';

export const FETCH_REPORT_USER_SUCCSESS = 'FETCH_REPORT_USER_SUCCSESS';
export const FETCH_REPORT_PRODUCT_SUCCSESS = 'FETCH_REPORT_PRODUCT_SUCCSESS';
export const FETCH_REPORT_PRODUCT_CATEGORY_SUCCSESS =
  'FETCH_REPORT_PRODUCT_CATEGORY_SUCCSESS';
export const FETCH_REPORT_ORDER_SUCCSESS = 'FETCH_REPORT_ORDER_SUCCSESS';

export const FETCH_REPORT_USER_FAILED = 'FETCH_REPORT_USER_FAILED';
export const FETCH_REPORT_PRODUCT_FAILED = 'FETCH_REPORT_PRODUCT_FAILED';
export const FETCH_REPORT_PRODUCT_CATEGORY_FAILED =
  'FETCH_REPORT_PRODUCT_CATEGORY_FAILED';
export const FETCH_REPORT_ORDER_FAILED = 'FETCH_REPORT_ORDER_FAILED';
