export const FILTER_SEARCH = 'FILTER_SEARCH ';
export const FILTER_PAGINATION = 'FILTER_PAGINATION';
export const FILTER_LIMIT = 'FILTER_LIMIT';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_PRICE_RANGE = 'FILTER_PRICE_RANGE';
export const FILTER_LAST_PAGE = 'FILTER_LAST_PAGE';
