export const ADD_CART = "SHOPPING_ADD_CART";
export const ADDING_CART = "SHOPPING_ADDING_CART";
export const ADDED_CART = "SHOPPING_ADDED_CART";
export const ADD_CART_CUCCESS = "ADD_CART_CUCCESS";
export const ADD_CART_FAILED = "ADD_CART_FAILED";
export const ADD_CART_RESET_STATUS_ADDING = "ADD_CART_RESET_STATUS_ADDING";
