export const ACTION_ADD_FILTERS = "YnmCrud/Search/ACTION_ADD_FILTERS";

export const ACTION_CHANGE_DATE_RANGE_FILTERS =
  "YnmCrud/Search/ACTION_CHANGE_DATE_RANGE_FILTERS";

export const ACTION_REPLACE_FILTERS = "YnmCrud/Search/ACTION_REPLACE_FILTERS";

export const ACTION_CLEAR_FILTERS = "YnmCrud/Search/ACTION_CLEAR_FILTERS";

export const ACTION_START_INIT_FILTERS = "YnmCrud/Search/START_INIT_FILTERS";

export const ACTION_INIT_FILTERS_SUCCESS =
  "YnmCrud/Search/INIT_FILTERS_SUCCESS";
