export const FETCH_DATA_USER = 'FETCH_DATA_USER';
export const FETCHING_DATA_USER = 'FETCHING_DATA_USER';
export const FETCHED_DATA_USER = 'FETCHED_DATA_USER';
export const SET_INFO_USER = 'SET_INFO_USER';
