export const crudOptionsDefault = {
  name: "crud",
  translateName: "name",
  endpoint: "hello",
  endpointParams: {},
  $eager: "owner",
  $sort: { id: -1 },
  extraFilters: {},
  mode: {
    breadcrumb: true,
    list: true,
    search: true,
    create: true,
    paging: true,
  },
  pagingOptions: {
    mode: "replace",
  },
  renderAddButotn: undefined,
  breadcrums: [{ label: "Excamples" }],
  headingOptions: [],
  schema: [
    {
      name: "id",
      label: "ID",
      default: "N/A",
      className: "text-center",
      width: "5%",
    },
    { name: "title", label: "Example title", default: "N/A" },
    {
      name: "project.name",
      label: "Project",
      default: "N/A",
      width: "20%",
    },
    {
      name: "description",
      label: "Description",
      default: "N/A",
      width: "30%",
      limit: 100,
    },
    {
      name: "created_at",
      // date: process.env.DATE_FORMAT_MEDIUM,
      label: "Created Date",
      default: "N/A",
      width: "20%",
    },
    {
      name: "options",
      label: "",
      options: [
        { name: "edit", label: "Edit", callback: null },
        { name: "delete", label: "Remove", callback: null },
      ],
    },
  ],
  formSchema: [
    {
      name: "title",
      label: "Example title",
      placeholder: "Example name",
      type: "text",
    },
    {
      type: "select",
      name: "id_project",
      label: "Project",
      isMulti: false,
      endpoint: "/app/projects",
    },
    {
      name: "description",
      label: "Description",
      placeholder: "Description (optional)",
      type: "textarea",
      rows: 5,
    },
  ],
  type: "list",
  showTotalItemsOnTop: true,
};
