export const DETAIL_FETCH_DATA = "DETAIL_FETCH_DATA";
export const DETAIL_FETCHING_DATA = "DETAIL_FETCHING_DATA";
export const DETAIL_SET_PRODUCT = "DETAIL_SET_PRODUCT";
export const DETAIL_FETCHED_DATA = "DETAIL_FETCHED_DATA";
export const DETAIL_FETCH_DATA_SUCCESS = "DETAIL_FETCH_DATA_SUCCESS";
export const DETAIL_FETCH_DATA_FAILED = "DETAIL_FETCH_DATA_FAILED";
export const DETAIL_RESET_STATUS_FETCH_DATA = "DETAIL_RESET_STATUS_FETCH_DATA";
